### ISSUE TITLE
JSS name clash causing issues with the Footer

### ISSUE THREAD

**Issue by karimkawambwa** [TakwimuAfrica/Takwimu.AFRICA#31]
**Describe the bug**

PT https://www.pivotaltracker.com/story/show/169497721

The jss class names are clashing and the the footer starts using the wrong styles.

<img width="1440" alt="Screen Shot 2019-11-01 at 10 19 23 AM" src="https://user-images.githubusercontent.com/4308339/68009022-c493f880-fc91-11e9-8dd4-cdbef5ef2a85.png">

**To Reproduce**
1. Go to https://beta.takwimu.africa/profiles/country-NG-nigeria#all
2. Scroll to bottom

**Expected behavior**

<img width="386" alt="Screen Shot 2019-11-01 at 10 20 47 AM" src="https://user-images.githubusercontent.com/4308339/68009035-cc539d00-fc91-11e9-9b55-591fa0af58fa.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

cc @kilemensi @KhadijaMahanga @DavidLemayian @nerdlet

**Comment by karimkawambwa** [comment]
@mtuchi

**Comment by kilemensi** [comment]
Fixed in https://github.com/TakwimuAfrica/Takwimu.AFRICA/pull/35
